class PhFileExtensions:
    TXT = '.txt'
    ASN = '.asn'
    ASN1 = '.asn1'
    BASE_64 = '.base64'
    HEX = '.hex'
    YML = '.yml'
    YAML = '.yaml'
    JSON = '.json'
    IN = '.in'
    OUT = '.out'
    CSV = '.csv'
    XLSX = '.xlsx'
    XLS = '.xls'
    PNG = '.png'
    SVG = '.svg'
    JPG = '.jpg'
    JPEG = '.jpeg'
