class Constants:
    STR_TYPE_PLAIN = 1
    STR_TYPE_HEX = 2
    STR_TYPE_NUMERIC = 3

    FILE_TYPE_IN = 1
    FILE_TYPE_OUT = 2

    MAX_SUPPORTED_DIGIT_IN_INT = 9
    FORMAT_HEX_STRING_AS_PACK = 1
    FORMAT_HEX_STRING_AS_HEX = 2
    FORMAT_HEX_STRING_AS_UPPERCASE = 4
    FORMAT_HEX_STRING_AS_COMMA = 8

    MODULE_PYCRATE_NAME = 'pycrate'
    MODULE_PYCRATE_VERSION_SUPPORTING_MULTI_LINE_COMMENTS = '0.5.4'
